# Faster command timeout for snappier prompts
command_timeout = 300
scan_timeout = 30

# Prompt format
format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$os $character"""

right_format = """
$python\
$nodejs\
$rust\
$golang\
$zig\
$lua\
$c\
$cpp\
$docker_context\
"""

[os]
format = "chigod($style)"
style = "white"
disabled = false


[directory]
truncation_length = 2
truncation_symbol = " "
style = "blue"

[character]
success_symbol = "[‚ùØ](purple)"
error_symbol = "[‚ùØ](red)"
vimcmd_symbol = "[‚ùÆ](green)"

[git_branch]
format = "on [$symbol$branch]($style)"
style = "red"
symbol = "Ôêò "

[git_status]
format = "[[( *$conflicted$untracked$modified$staged$renamed$deleted)](218)($ahead_behind$stashed)]($style)"
style = "green"
conflicted = "="
untracked = "?"
modified = "!"
staged = "+"
renamed = "¬ª"
deleted = "‚úò"
stashed = "$"
ahead = "‚á°"
behind = "‚á£"
diverged = "‚áï"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"
rebase = "‚ü≥"
merge = ""
revert = "‚éå"
cherry_pick = ""
bisect = ""
am = "‚úâ"
am_or_rebase = "‚úâ‚ü≥"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[python]
format = '[${symbol}${version}(\($virtualenv\))]($style)'
symbol = "Óàµ "
style = "bright-green"
pyenv_version_name = false
detect_extensions = ["py"]
detect_files = ["requirements.txt", "pyproject.toml", ".python-version", "Pipfile", "setup.py"]

[docker_context]
format = ' [${symbol}${context}]($style)'
symbol = 'üê≥ '
only_with_files = true

[nodejs]
format = '[${symbol}${version}]($style) '
symbol = ' '
style = "green"
detect_extensions = ["js", "mjs", "cjs", "ts"]
detect_files = ["package.json", ".node-version"]
detect_folders = ["node_modules"]

[rust]
format = '[${symbol}${version}]($style) '
symbol = ' '
style = "red"
detect_extensions = ["rs"]
detect_files = ["Cargo.toml"]

[golang]
format = '[${symbol}${version}]($style) '
symbol = ' '
style = "cyan"
detect_extensions = ["go"]
detect_files = ["go.mod", "go.sum"]

[zig]
format = '[${symbol}${version}]($style) '
symbol = ' '
style = "yellow"
detect_extensions = ["zig"]
detect_files = ["build.zig"]

[lua]
format = '[${symbol}${version}]($style) '
symbol = ' '
style = "blue"
detect_extensions = ["lua"]
detect_files = [".lua-version", ".luacheckrc", ".luarc.json"]

[c]
format = '[${symbol}${version}]($style) '
symbol = ' '
style = "blue"
detect_extensions = ["c", "h"]
detect_files = ["Makefile"]

[cpp]
format = '[${symbol}${version}]($style) '
symbol = ' '
style = "blue"
detect_extensions = ["cpp", "cc", "cxx", "hpp", "hh", "hxx"]
detect_files = ["CMakeLists.txt", "meson.build"]
