# Faster command timeout for snappier prompts
command_timeout = 300
scan_timeout = 30

# Prompt format
format = """
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$cmd_duration\
$line_break\
$os $character"""

[os]
format = "chigod($style)"
style = "white"
disabled = false


[directory]
truncation_length = 2
truncation_symbol = ""
style = "blue"

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[git_branch]
format = "on [$symbol$branch ]($style)"
style = "red"
symbol = " "

[git_status]
format = "[[($conflicted$untracked$modified$staged$renamed$deleted)](218)($ahead_behind$stashed)]($style)"
style = "green"
conflicted = "⚠ "
untracked = "✚ "
modified = "✎ "
staged = "+ "
renamed = "⇄ "
deleted = "✘ "
stashed = "≡ "
ahead = "↑ "
behind = "↓ "
diverged = "⇅ "

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"
