format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$os $character"""

right_format = """
$python
$docker_context
"""

[os]
format = "chigod($style)"
style = "white"
disabled = false


[directory]
truncation_length = 2
truncation_symbol = " "
style = "blue"

[character]
success_symbol = "[â¯](purple)"
error_symbol = "[â¯](red)"
vimcmd_symbol = "[â®](green)"

[git_branch]
format = "on [$symbol$branch]($style)"
style = "red"
symbol = "ï˜ "

[git_status]
format = "[[( *$conflicted$untracked$modified$staged$renamed$deleted)](218)($ahead_behind$stashed)]($style)"
style = "green"
conflicted = "âŒ"
untracked = "ğŸŒ±"
modified = "âœ”"
staged = "+"
renamed = "ğŒ¡"
deleted = "X"
stashed = "â‰¡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[python]
format = '[${symbol}${version}(\($virtualenv\))]($style)'
symbol = "îˆµ "
style = "bright-green"

[docker_context]
format = ' [${symbol}${context}]($style)'
symbol = 'ğŸ³'


